### ISSUE TITLE
ux: unable to dismiss the settings modal on Mobile

### ISSUE THREAD

**Issue by tomholford** [urbit/garden#26] opened 2022-12-15 02:24 UTC
Clicking the sigil button when the modal is open should close it 

![image](https://user-images.githubusercontent.com/16504501/207757541-40bf1486-61f5-4d32-b93b-cc55eb18d22b.jpeg)

**Comment by jamesacklin** [comment] 2022-12-15 16:16
Dupe of #1372

**Closed by jamesacklin** 2022-12-15 16:16 UTC
Labels: bug
